<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo Mage::helper('adminhtml')->__('Admin Page Login'); ?></title>
    <style type="text/css">
        pre {
            padding: 1em;
        }
        form {
        <?php if($this->getFormColor()): ?>
            background-color : <?php echo $this->getFormColor()?>;
        <?php endif; ?>
            width : 22em;
            margin : 10em auto;
        }
        input {
            width : 15em;
        }
    </style>
</head>
<form method="post" action="" autocomplete="<?php echo $this->getAutoComplete(); ?>">
<pre>
<input name="form_key" type="hidden" value="<?php echo $this->getFormKey(); ?>" />
<strong><?php echo Mage::helper('adminhtml')->__('Forgot your user name or password?'); ?></strong><?php

    $msg = trim(strip_tags($this->getMessagesBlock()->getGroupedHtml()));
    echo !empty($msg)
        ? "\n\n" . $msg
        : '';
    ?>


<?php echo Mage::helper('adminhtml')->__('Email Address:'); ?> <input type="text" name="email" value="" />
<?php echo $this->getChildHtml('form.additional.info'); ?>

<input type="submit" value="<?php echo Mage::helper('adminhtml')->__('Retrieve Password') ?>" title="<?php echo Mage::helper('adminhtml')->__('Retrieve Password') ?>"/>

<a href="<?php echo $this->getUrl('adminhtml', array('_nosecret' => true)); ?>">&laquo; <?php echo Mage::helper('adminhtml')->__('Back to Login'); ?></a>
</pre>
</form>
</body>
</html>

