<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title><?php echo Mage::helper('adminhtml')->__('Admin Page Login') ?></title>
    <style type="text/css">
        pre {
            padding: 1em;
        }
        form {
        <?php if($this->getFormColor()): ?>
            background-color : <?php echo $this->getFormColor()?>;
        <?php endif; ?>
            width : 22em;
            margin : 10em auto;
        }
        input {
            width : 10em;
        }
    </style>
</head>
<body>
<form method="post" action="" autocomplete="<?php echo $this->getAutoComplete(); ?>">
    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>"/>
<pre>
<strong><?php echo Mage::helper('adminhtml')->__('Admin Panel Login') ?></strong><?php

    $msg = trim(strip_tags($this->getMessagesBlock()->getGroupedHtml()));
    echo !empty($msg)
        ? "\n\n" . $msg
        : '';
    ?>

<?php echo Mage::helper('adminhtml')->__('User Name:') ?> <input type="text" id="username" name="login[username]" value=""/>
<?php echo Mage::helper('adminhtml')->__('Password:') ?>  <input type="password" id="login" name="login[password]" value=""/>
<?php echo $this->getChildHtml('form.additional.info'); ?>
           <input type="submit" value="<?php echo Mage::helper('adminhtml')->__('Login') ?>" title="<?php echo Mage::helper('adminhtml')->__('Login') ?>"/>

<?php if (!$this->getDisableForgotPasswordLink()): ?>
<a href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/index/forgotpassword', array('_nosecret' => true)) ?>"><?php echo Mage::helper('adminhtml')->__('Forgot your password?') ?></a>
<?php endif; ?>
</pre>
</form>
</body>
</html>

