<?php $captcha = $this->getCaptchaModel() ?>
<?php /* @var $this Mage_Core_Block_Captcha_Zend */ ?>

<?php echo $this->__('Please type the letters from the image:') ?>

<input type="text" name="<?php echo Mage_Captcha_Helper_Data::INPUT_NAME_FIELD_VALUE;  ?>[<?php echo $this->getFormId()?>]"/>

<img id="<?php echo $this->getFormId() ?>" width="<?php echo $this->getImgWidth() ?>" height="<?php echo $this->getImgHeight() ?>" src="<?php echo $captcha->getImgSrc() ?>" />
